import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../../core/config/supabase_client.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/ui/responsive.dart';
import '../../../core/widgets/error_widget.dart';
import '../../../core/widgets/loading_widget.dart';
import '../../inventory/providers/inventory_provider.dart';
import '../../inventory/data/models/supplier_model.dart';
import '../../vendors/screens/vendor_analytics_dashboard.dart';
import '../data/models/report_models.dart';
import '../providers/report_provider.dart';

class ReportsScreen extends ConsumerStatefulWidget {
  final String? projectId;

  const ReportsScreen({super.key, this.projectId});

  @override
  ConsumerState<ReportsScreen> createState() => _ReportsScreenState();
}

class _ReportsScreenState extends ConsumerState<ReportsScreen> {
  bool _isExporting = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      ref
          .read(reportProvider.notifier)
          .loadReports(projectId: widget.projectId);
    });
  }

  Future<void> _exportPdf(ReportState state) async {
    if (_isExporting) return;
    setState(() => _isExporting = true);
    try {
      final doc = pw.Document();
      final stats = state.stats;
      final generatedAt = DateTime.now();

      doc.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (pw.Context ctx) => [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Project Insights Report',
                  style: pw.TextStyle(
                      fontSize: 22, fontWeight: pw.FontWeight.bold),
                ),
                pw.Text(
                  '${generatedAt.day}/${generatedAt.month}/${generatedAt.year}',
                  style: const pw.TextStyle(
                      fontSize: 11, color: PdfColors.grey600),
                ),
              ],
            ),
            if (widget.projectId != null)
              pw.Text(
                'Project ID: ${widget.projectId}',
                style: const pw.TextStyle(
                    fontSize: 10, color: PdfColors.grey500),
              ),
            pw.SizedBox(height: 16),
            pw.Divider(),
            pw.SizedBox(height: 12),
            pw.Text('Financial Summary',
                style: pw.TextStyle(
                    fontSize: 16, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            _pdfRow('Total Expenses',
                '₹${stats.totalExpenses.toStringAsFixed(2)}'),
            _pdfRow(
                'Labour Cost', '₹${stats.laborCost.toStringAsFixed(2)}'),
            _pdfRow('Material Cost',
                '₹${stats.materialCost.toStringAsFixed(2)}'),
            _pdfRow('Machinery Cost',
                '₹${stats.machineryCost.toStringAsFixed(2)}'),
            _pdfRow(
                'Other Cost', '₹${stats.otherCost.toStringAsFixed(2)}'),
            pw.SizedBox(height: 16),
            if (stats.chartData.isNotEmpty) ...[
              pw.Text('Monthly Breakdown',
                  style: pw.TextStyle(
                      fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              pw.TableHelper.fromTextArray(
                headers: ['Period', 'Amount (₹)'],
                data: stats.chartData
                    .map((d) => [d.label, d.value.toStringAsFixed(2)])
                    .toList(),
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                cellAlignment: pw.Alignment.centerLeft,
                headerDecoration:
                    const pw.BoxDecoration(color: PdfColors.blueGrey100),
              ),
              pw.SizedBox(height: 16),
            ],
            pw.Divider(),
            pw.SizedBox(height: 8),
            pw.Text(
              'Generated by SiteOS · ${generatedAt.toIso8601String()}',
              style: const pw.TextStyle(
                  fontSize: 9, color: PdfColors.grey500),
            ),
          ],
        ),
      );

      await Printing.layoutPdf(
        onLayout: (_) async => doc.save(),
        name:
            'report_${widget.projectId ?? "all"}_${generatedAt.millisecondsSinceEpoch}.pdf',
      );
    } catch (e) {
      logger.e('PDF export failed: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
              content: Text('Export failed: $e'),
              backgroundColor: AppColors.error),
        );
      }
    } finally {
      if (mounted) setState(() => _isExporting = false);
    }
  }

  pw.Widget _pdfRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 11)),
          pw.Text(value,
              style: pw.TextStyle(
                  fontSize: 11, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(reportProvider);
    final notifier = ref.read(reportProvider.notifier);
    final suppliersAsync = ref.watch(suppliersProvider);

    return Scaffold(
      backgroundColor: AppColors.scaffoldBackground,
      body: LayoutBuilder(
        builder: (context, constraints) {
          final r = R(Size(constraints.maxWidth, constraints.maxHeight));

          return SafeArea(
            child: RefreshIndicator(
              onRefresh: () =>
                  notifier.refresh(projectId: widget.projectId),
              child: SingleChildScrollView(
                padding: EdgeInsets.fromLTRB(
                  r.isDesktop ? 32 : 20,
                  r.isDesktop ? 28 : 8,
                  r.isDesktop ? 32 : 20,
                  r.isDesktop ? 28 : 16,
                ),
                child: Align(
                  alignment: Alignment.topCenter,
                  child: ConstrainedBox(
                    constraints:
                        BoxConstraints(maxWidth: r.maxContentWidth),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Header
                        _buildHeader(context, state),
                        const SizedBox(height: 20),

                        // Filters
                        _buildFilters(context, state, notifier,
                            suppliersAsync),
                        const SizedBox(height: 24),

                        if (state.isLoading &&
                            state.stats == FinancialStats.empty)
                          const LoadingWidget(
                              message: 'Loading insights...')
                        else if (state.error != null &&
                            state.stats == FinancialStats.empty)
                          AppErrorWidget(
                            message: state.error!,
                            onRetry: () => notifier.refresh(),
                          )
                        else ...[
                          // KPI summary row
                          _KpiSummaryRow(stats: state.stats),
                          const SizedBox(height: 20),

                          // Desktop: side-by-side charts
                          if (r.isDesktop)
                            Row(
                              crossAxisAlignment:
                                  CrossAxisAlignment.start,
                              children: [
                                Expanded(
                                    flex: 3,
                                    child: _FinancialHealthCard(
                                        stats: state.stats)),
                                const SizedBox(width: 20),
                                Expanded(
                                    flex: 2,
                                    child: _ResourceSplitCard(
                                        stats: state.stats)),
                              ],
                            )
                          else ...[
                            _FinancialHealthCard(stats: state.stats),
                            const SizedBox(height: 16),
                            _ResourceSplitCard(stats: state.stats),
                          ],
                          const SizedBox(height: 20),

                          // Project-wise breakdown (only on global reports)
                          if (widget.projectId == null) ...[
                            _ProjectBreakdownSection(
                              materialRows: state.materialVendors,
                              machineryRows: state.machineryProjects,
                              labourRows: state.labourProjects,
                              isLoading: state.isLoading,
                            ),
                            const SizedBox(height: 20),
                            _VendorAnalyticsSection(),
                            const SizedBox(height: 20),
                          ],

                          _OperationsReports(
                            materialRows: state.materialVendors,
                            machineryRows: state.machineryProjects,
                            labourRows: state.labourProjects,
                            isLoading: state.isLoading,
                          ),
                          const SizedBox(height: 20),

                          if (state.stats.growthPercentage != 0)
                            _InsightTip(
                                growth: state.stats.growthPercentage),

                          const SizedBox(height: 40),
                        ],
                      ],
                    ),
                  ),
                ),
              ),
            ),
          );
        },
      ),
    );
  }

  Widget _buildHeader(BuildContext context, ReportState state) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.end,
      children: [
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'ANALYTICS',
              style: GoogleFonts.plusJakartaSans(
                fontSize: 11,
                fontWeight: FontWeight.w700,
                color: AppColors.secondaryDark,
                letterSpacing: 2.2,
              ),
            ),
            const SizedBox(height: 6),
            Text(
              'Reports',
              style: GoogleFonts.fraunces(
                fontSize: 32,
                fontWeight: FontWeight.w400,
                color: AppColors.textPrimary,
                letterSpacing: -1.0,
                height: 1.0,
              ),
            ),
            if (widget.projectId != null) ...[
              const SizedBox(height: 6),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: AppColors.primary.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  'Project',
                  style: TextStyle(
                    fontSize: 11,
                    fontWeight: FontWeight.w600,
                    color: AppColors.primary,
                  ),
                ),
              ),
            ],
          ],
        ),
        const Spacer(),
        Material(
          color: Colors.white,
          borderRadius: BorderRadius.circular(10),
          child: InkWell(
            onTap: _isExporting ? null : () => _exportPdf(state),
            borderRadius: BorderRadius.circular(10),
            child: Container(
              height: 40,
              padding: const EdgeInsets.symmetric(horizontal: 14),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(10),
                border: Border.all(color: AppColors.border),
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  if (_isExporting)
                    const SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  else
                    Icon(Icons.download_rounded,
                        size: 17, color: AppColors.textPrimary),
                  const SizedBox(width: 6),
                  Text(
                    'Export',
                    style: TextStyle(
                      fontSize: 13,
                      fontWeight: FontWeight.w600,
                      color: AppColors.textPrimary,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildFilters(
    BuildContext context,
    ReportState state,
    ReportNotifier notifier,
    AsyncValue<List<SupplierModel>> suppliersAsync,
  ) {
    return Column(
      children: [
        // Time period tabs
        Container(
          height: 42,
          decoration: BoxDecoration(
            color: AppColors.surfaceVariant,
            borderRadius: BorderRadius.circular(10),
          ),
          padding: const EdgeInsets.all(3),
          child: Row(
            children: TimePeriod.values.map((period) {
              final isSelected = state.selectedPeriod == period;
              return Expanded(
                child: GestureDetector(
                  onTap: () => notifier.setPeriod(period,
                      projectId: widget.projectId),
                  child: AnimatedContainer(
                    duration: const Duration(milliseconds: 150),
                    alignment: Alignment.center,
                    decoration: BoxDecoration(
                      color:
                          isSelected ? Colors.white : Colors.transparent,
                      borderRadius: BorderRadius.circular(8),
                      boxShadow: isSelected
                          ? const [
                              BoxShadow(
                                color: Color(0x0A000000),
                                blurRadius: 4,
                                offset: Offset(0, 1),
                              ),
                            ]
                          : null,
                    ),
                    child: Text(
                      period.label,
                      style: TextStyle(
                        fontWeight: isSelected
                            ? FontWeight.w600
                            : FontWeight.w500,
                        color: isSelected
                            ? AppColors.textPrimary
                            : AppColors.textSecondary,
                        fontSize: 13,
                      ),
                    ),
                  ),
                ),
              );
            }).toList(),
          ),
        ),
        const SizedBox(height: 12),

        // Vendor filter
        suppliersAsync.when(
          data: (suppliers) => _VendorFilter(
            suppliers: suppliers,
            selectedVendorId: state.selectedVendorId,
            onChanged: (vendorId) =>
                notifier.setVendor(vendorId, projectId: widget.projectId),
          ),
          loading: () => const SizedBox.shrink(),
          error: (_, _) => const SizedBox.shrink(),
        ),
      ],
    );
  }
}

// ── KPI Summary Row ──

class _KpiSummaryRow extends StatelessWidget {
  final FinancialStats stats;
  const _KpiSummaryRow({required this.stats});

  @override
  Widget build(BuildContext context) {
    final items = [
      _KpiItem(
        label: 'Total Spend',
        value: _fmt(stats.totalExpenses),
        icon: Icons.currency_rupee_rounded,
        color: AppColors.primary,
      ),
      _KpiItem(
        label: 'Labour',
        value: _fmt(stats.laborCost),
        icon: Icons.people_outline_rounded,
        color: AppColors.warning,
      ),
      _KpiItem(
        label: 'Material',
        value: _fmt(stats.materialCost),
        icon: Icons.inventory_2_outlined,
        color: AppColors.success,
      ),
      _KpiItem(
        label: 'Machinery',
        value: _fmt(stats.machineryCost),
        icon: Icons.precision_manufacturing_outlined,
        color: AppColors.info,
      ),
    ];

    return GridView.count(
      crossAxisCount: 2,
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      crossAxisSpacing: 12,
      mainAxisSpacing: 12,
      childAspectRatio: 2.2,
      children: items.map((item) => _KpiCard(item: item)).toList(),
    );
  }

  String _fmt(double v) => v >= 100000
      ? '₹${(v / 100000).toStringAsFixed(1)}L'
      : v >= 1000
          ? '₹${(v / 1000).toStringAsFixed(0)}K'
          : '₹${v.toStringAsFixed(0)}';
}

class _KpiItem {
  final String label;
  final String value;
  final IconData icon;
  final Color color;
  const _KpiItem({required this.label, required this.value, required this.icon, required this.color});
}

class _KpiCard extends StatelessWidget {
  final _KpiItem item;
  const _KpiCard({required this.item});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppColors.borderDark.withValues(alpha: 0.4)),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: item.color.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(item.icon, size: 18, color: item.color),
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  item.value,
                  style: TextStyle(
                    fontSize: 15,
                    fontWeight: FontWeight.w800,
                    color: AppColors.textPrimary,
                    letterSpacing: -0.3,
                  ),
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
                const SizedBox(height: 2),
                Text(
                  item.label,
                  style: TextStyle(
                    fontSize: 11,
                    color: AppColors.textSecondary,
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ── Project-wise Breakdown ──

class _ProjectBreakdownSection extends StatelessWidget {
  final List<MaterialVendorReportRow> materialRows;
  final List<MachineryProjectReportRow> machineryRows;
  final List<LabourProjectReportRow> labourRows;
  final bool isLoading;

  const _ProjectBreakdownSection({
    required this.materialRows,
    required this.machineryRows,
    required this.labourRows,
    required this.isLoading,
  });

  @override
  Widget build(BuildContext context) {
    // Aggregate material count per project
    final Map<String, int> materialByProject = {};
    for (final r in materialRows) {
      materialByProject[r.projectName] =
          (materialByProject[r.projectName] ?? 0) + 1;
    }

    // Aggregate machinery hours per project
    final Map<String, double> machineryByProject = {};
    for (final r in machineryRows) {
      machineryByProject[r.projectName] =
          (machineryByProject[r.projectName] ?? 0) + r.totalHours;
    }

    // Aggregate labour count per project
    final Map<String, int> labourByProject = {};
    for (final r in labourRows) {
      labourByProject[r.projectName] =
          (labourByProject[r.projectName] ?? 0) + 1;
    }

    // Union of all project names
    final allProjects = <String>{
      ...materialByProject.keys,
      ...machineryByProject.keys,
      ...labourByProject.keys,
    }.toList()..sort();

    if (allProjects.isEmpty) return const SizedBox.shrink();

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: AppColors.borderDark.withValues(alpha: 0.5)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.bar_chart_rounded, size: 18, color: AppColors.textSecondary),
              const SizedBox(width: 8),
              Text(
                'Project-wise Breakdown',
                style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                      fontWeight: FontWeight.w700,
                    ),
              ),
              if (isLoading) ...[
                const Spacer(),
                const SizedBox(
                  height: 14,
                  width: 14,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
              ],
            ],
          ),
          const SizedBox(height: 4),
          Text(
            'Resource activity across all active projects',
            style: Theme.of(context).textTheme.bodySmall?.copyWith(
                  color: AppColors.textSecondary,
                ),
          ),
          const SizedBox(height: 18),
          ...allProjects.map((project) {
            final mCount = materialByProject[project] ?? 0;
            final mHours = machineryByProject[project] ?? 0;
            final lCount = labourByProject[project] ?? 0;
            return _ProjectBreakdownRow(
              projectName: project,
              materialCount: mCount,
              machineryHours: mHours,
              labourCount: lCount,
            );
          }),
        ],
      ),
    );
  }
}

class _ProjectBreakdownRow extends StatelessWidget {
  final String projectName;
  final int materialCount;
  final double machineryHours;
  final int labourCount;

  const _ProjectBreakdownRow({
    required this.projectName,
    required this.materialCount,
    required this.machineryHours,
    required this.labourCount,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                width: 6,
                height: 6,
                decoration: const BoxDecoration(
                  color: AppColors.primary,
                  shape: BoxShape.circle,
                ),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  projectName,
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                        fontWeight: FontWeight.w700,
                        color: AppColors.textPrimary,
                      ),
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
            ],
          ),
          const SizedBox(height: 6),
          Padding(
            padding: const EdgeInsets.only(left: 14),
            child: Wrap(
              spacing: 8,
              runSpacing: 4,
              children: [
                if (materialCount > 0)
                  _ProjectBadge(
                    icon: Icons.inventory_2_outlined,
                    label: '$materialCount material${materialCount > 1 ? "s" : ""}',
                    color: AppColors.success,
                  ),
                if (machineryHours > 0)
                  _ProjectBadge(
                    icon: Icons.precision_manufacturing_outlined,
                    label: '${machineryHours.toStringAsFixed(0)} machinery hrs',
                    color: AppColors.primary,
                  ),
                if (labourCount > 0)
                  _ProjectBadge(
                    icon: Icons.people_outline_rounded,
                    label: '$labourCount worker${labourCount > 1 ? "s" : ""}',
                    color: AppColors.warning,
                  ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _ProjectBadge extends StatelessWidget {
  final IconData icon;
  final String label;
  final Color color;
  const _ProjectBadge({required this.icon, required this.label, required this.color});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(6),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 11, color: color),
          const SizedBox(width: 4),
          Text(
            label,
            style: TextStyle(
              fontSize: 11,
              fontWeight: FontWeight.w600,
              color: color,
            ),
          ),
        ],
      ),
    );
  }
}

// ── Financial Health Card ──

class _FinancialHealthCard extends StatelessWidget {
  final FinancialStats stats;
  const _FinancialHealthCard({required this.stats});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(22),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border:
            Border.all(color: AppColors.borderDark.withValues(alpha: 0.5)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Text(
                'Financial Health',
                style: Theme.of(context).textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.w700,
                    ),
              ),
              const Spacer(),
              Container(
                padding: const EdgeInsets.symmetric(
                    horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: (stats.growthPercentage >= 0
                          ? AppColors.success
                          : AppColors.error)
                      .withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(6),
                ),
                child: Text(
                  '${stats.growthPercentage >= 0 ? '+' : ''}${stats.growthPercentage}%',
                  style: TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.w700,
                    color: stats.growthPercentage >= 0
                        ? AppColors.success
                        : AppColors.error,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 4),
          Row(
            crossAxisAlignment: CrossAxisAlignment.baseline,
            textBaseline: TextBaseline.alphabetic,
            children: [
              Text(
                '₹${stats.totalExpenses >= 100000 ? '${(stats.totalExpenses / 100000).toStringAsFixed(1)}L' : stats.totalExpenses.toStringAsFixed(0)}',
                style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                      fontWeight: FontWeight.w800,
                    ),
              ),
              const SizedBox(width: 6),
              Text(
                'total expenses',
                style: Theme.of(context).textTheme.bodySmall?.copyWith(
                      color: AppColors.textHint,
                    ),
              ),
            ],
          ),
          const SizedBox(height: 20),
          SizedBox(
            height: 180,
            child: LineChart(
              LineChartData(
                gridData: FlGridData(show: false),
                titlesData: FlTitlesData(
                  bottomTitles: AxisTitles(
                    sideTitles: SideTitles(
                      showTitles: true,
                      getTitlesWidget: (value, meta) {
                        if (stats.chartData.isEmpty) {
                          return const SizedBox.shrink();
                        }
                        final index = value.toInt();
                        if (index < 0 || index >= stats.chartData.length) {
                          return const SizedBox.shrink();
                        }
                        if (stats.chartData.length > 6 && index % 2 != 0) {
                          return const SizedBox.shrink();
                        }
                        return Padding(
                          padding: const EdgeInsets.only(top: 8),
                          child: Text(
                            stats.chartData[index].label,
                            style: const TextStyle(
                              color: AppColors.textSecondary,
                              fontSize: 10,
                            ),
                          ),
                        );
                      },
                      reservedSize: 22,
                    ),
                  ),
                  leftTitles:
                      AxisTitles(sideTitles: SideTitles(showTitles: false)),
                  topTitles:
                      AxisTitles(sideTitles: SideTitles(showTitles: false)),
                  rightTitles:
                      AxisTitles(sideTitles: SideTitles(showTitles: false)),
                ),
                borderData: FlBorderData(show: false),
                lineBarsData: [
                  LineChartBarData(
                    spots: stats.chartData.asMap().entries.map((e) {
                      return FlSpot(e.key.toDouble(), e.value.value);
                    }).toList(),
                    isCurved: true,
                    color: AppColors.primary,
                    barWidth: 2.5,
                    isStrokeCapRound: true,
                    dotData: FlDotData(show: false),
                    belowBarData: BarAreaData(
                      show: true,
                      color: AppColors.primary.withValues(alpha: 0.08),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Resource Split Card ──

class _ResourceSplitCard extends StatelessWidget {
  final FinancialStats stats;
  const _ResourceSplitCard({required this.stats});

  @override
  Widget build(BuildContext context) {
    final total = stats.laborCost +
        stats.materialCost +
        stats.machineryCost +
        stats.otherCost;
    final safeTotal = total > 0 ? total : 1.0;

    return Container(
      padding: const EdgeInsets.all(22),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border:
            Border.all(color: AppColors.borderDark.withValues(alpha: 0.5)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Resource Split',
            style: Theme.of(context).textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.w700,
                ),
          ),
          const SizedBox(height: 24),
          Center(
            child: SizedBox(
              height: 120,
              width: 120,
              child: PieChart(
                PieChartData(
                  sectionsSpace: 2,
                  centerSpaceRadius: 38,
                  sections: [
                    PieChartSectionData(
                      color: AppColors.warning,
                      value: stats.laborCost,
                      title: '',
                      radius: 14,
                    ),
                    PieChartSectionData(
                      color: AppColors.success,
                      value: stats.materialCost,
                      title: '',
                      radius: 14,
                    ),
                    PieChartSectionData(
                      color: AppColors.primary,
                      value: stats.machineryCost,
                      title: '',
                      radius: 14,
                    ),
                  ],
                ),
              ),
            ),
          ),
          const SizedBox(height: 24),
          _LegendItem(
            color: AppColors.warning,
            label: 'Labour',
            amount: stats.laborCost,
            percentage: (stats.laborCost / safeTotal * 100).round(),
          ),
          const SizedBox(height: 10),
          _LegendItem(
            color: AppColors.success,
            label: 'Material',
            amount: stats.materialCost,
            percentage: (stats.materialCost / safeTotal * 100).round(),
          ),
          const SizedBox(height: 10),
          _LegendItem(
            color: AppColors.primary,
            label: 'Machinery',
            amount: stats.machineryCost,
            percentage: (stats.machineryCost / safeTotal * 100).round(),
          ),
        ],
      ),
    );
  }
}

class _LegendItem extends StatelessWidget {
  final Color color;
  final String label;
  final double amount;
  final int percentage;

  const _LegendItem({
    required this.color,
    required this.label,
    required this.amount,
    required this.percentage,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Container(
          width: 10,
          height: 10,
          decoration: BoxDecoration(
            color: color,
            borderRadius: BorderRadius.circular(3),
          ),
        ),
        const SizedBox(width: 10),
        Expanded(
          child: Text(
            label,
            style: Theme.of(context).textTheme.bodySmall?.copyWith(
                  fontWeight: FontWeight.w500,
                  color: AppColors.textPrimary,
                ),
          ),
        ),
        Text(
          '$percentage%',
          style: Theme.of(context).textTheme.bodySmall?.copyWith(
                fontWeight: FontWeight.w700,
                color: AppColors.textSecondary,
              ),
        ),
      ],
    );
  }
}

// ── Insight Tip ──

class _InsightTip extends StatelessWidget {
  final double growth;
  const _InsightTip({required this.growth});

  @override
  Widget build(BuildContext context) {
    if (growth == 0) return const SizedBox.shrink();
    final isPositive = growth > 0;

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppColors.primary.withValues(alpha: 0.06),
        borderRadius: BorderRadius.circular(14),
        border: Border.all(
            color: AppColors.primary.withValues(alpha: 0.15)),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: AppColors.primary.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(Icons.lightbulb_outline_rounded,
                color: AppColors.primary, size: 20),
          ),
          const SizedBox(width: 14),
          Expanded(
            child: Text(
              'Your projects are running ${growth.abs()}% ${isPositive ? 'higher' : 'lower'} than last period targets.',
              style: Theme.of(context).textTheme.bodySmall?.copyWith(
                    color: AppColors.textPrimary,
                    height: 1.4,
                  ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Vendor Analytics Section ──

class _VendorAnalyticsSection extends StatelessWidget {
  const _VendorAnalyticsSection();

  @override
  Widget build(BuildContext context) {
    return Material(
      color: AppColors.sidebarBackground,
      borderRadius: BorderRadius.circular(14),
      child: InkWell(
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (_) => const VendorAnalyticsDashboard(),
            ),
          );
        },
        borderRadius: BorderRadius.circular(14),
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Row(
            children: [
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.white.withValues(alpha: 0.12),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Icon(Icons.storefront_outlined,
                    color: Colors.white, size: 24),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Vendor Analytics',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 16,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    const SizedBox(height: 3),
                    Text(
                      'Payment tracking · Stock history · Credit limits',
                      style: TextStyle(
                        color: Colors.white.withValues(alpha: 0.7),
                        fontSize: 12,
                      ),
                    ),
                  ],
                ),
              ),
              Icon(Icons.arrow_forward_ios_rounded,
                  color: Colors.white.withValues(alpha: 0.5), size: 16),
            ],
          ),
        ),
      ),
    );
  }
}

// ── Vendor Filter ──

class _VendorFilter extends StatelessWidget {
  final List<SupplierModel> suppliers;
  final String? selectedVendorId;
  final ValueChanged<String?> onChanged;

  const _VendorFilter({
    required this.suppliers,
    required this.selectedVendorId,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 42,
      child: DropdownButtonFormField<String?>(
        initialValue: selectedVendorId,
        decoration: InputDecoration(
          labelText: 'Vendor',
          isDense: true,
          contentPadding:
              const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          border:
              OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10),
            borderSide: const BorderSide(color: AppColors.border),
          ),
          filled: true,
          fillColor: AppColors.surface,
        ),
        style: const TextStyle(fontSize: 13, color: AppColors.textPrimary),
        items: [
          const DropdownMenuItem<String?>(
              value: null, child: Text('All vendors')),
          ...suppliers.map(
            (s) => DropdownMenuItem<String?>(
                value: s.id, child: Text(s.name)),
          ),
        ],
        onChanged: onChanged,
      ),
    );
  }
}

// ── Operations Reports ──

class _OperationsReports extends StatelessWidget {
  final List<MaterialVendorReportRow> materialRows;
  final List<MachineryProjectReportRow> machineryRows;
  final List<LabourProjectReportRow> labourRows;
  final bool isLoading;

  const _OperationsReports({
    required this.materialRows,
    required this.machineryRows,
    required this.labourRows,
    required this.isLoading,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Operations',
          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w700,
              ),
        ),
        const SizedBox(height: 14),
        _ReportCard(
          icon: Icons.inventory_2_outlined,
          title: 'Material by Vendor & Project',
          isLoading: isLoading,
          child: materialRows.isEmpty
              ? const _EmptyRow(message: 'No material receipts yet')
              : Column(
                  children: materialRows.take(6).map((row) {
                    return _TwoLineTile(
                      title: '${row.materialName} · ${row.vendorName}',
                      subtitle:
                          '${row.projectName} · ${row.totalReceived.toStringAsFixed(1)} ${row.unit}',
                      trailing: row.lastReceivedAt != null
                          ? _dateLabel(row.lastReceivedAt!)
                          : '',
                    );
                  }).toList(),
                ),
        ),
        const SizedBox(height: 12),
        _ReportCard(
          icon: Icons.precision_manufacturing_outlined,
          title: 'Machinery by Project',
          isLoading: isLoading,
          child: machineryRows.isEmpty
              ? const _EmptyRow(message: 'No machinery logs yet')
              : Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _OperationsBarChart(
                      items: machineryRows.take(6).map((r) {
                        return _BarItem(
                          label:
                              '${r.machineryName}${r.machineryType.isNotEmpty ? ' (${r.machineryType})' : ''}',
                          value: r.totalHours,
                          unit: 'hrs',
                        );
                      }).toList(),
                      barColor: AppColors.primary,
                    ),
                    const SizedBox(height: 8),
                    ...machineryRows.take(6).map((row) {
                      return _TwoLineTile(
                        title:
                            '${row.machineryName}${row.machineryType.isNotEmpty ? ' (${row.machineryType})' : ''}',
                        subtitle:
                            '${row.projectName} · ${row.totalHours.toStringAsFixed(1)} hrs',
                        trailing: row.lastWorkedAt != null
                            ? _dateLabel(row.lastWorkedAt!)
                            : '',
                      );
                    }),
                  ],
                ),
        ),
        const SizedBox(height: 12),
        _ReportCard(
          icon: Icons.people_outline_rounded,
          title: 'Labour by Project',
          isLoading: isLoading,
          child: labourRows.isEmpty
              ? const _EmptyRow(message: 'No active labour found')
              : Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _OperationsBarChart(
                      items: labourRows.take(6).map((r) {
                        return _BarItem(
                          label:
                              '${r.labourName}${r.skillType.isNotEmpty ? ' · ${r.skillType}' : ''}',
                          value: r.dailyWage,
                          unit: '₹/day',
                        );
                      }).toList(),
                      barColor: AppColors.accent,
                    ),
                    const SizedBox(height: 8),
                    ...labourRows.take(6).map((row) {
                      final wage = row.dailyWage > 0
                          ? '₹${row.dailyWage.toStringAsFixed(0)}/day'
                          : '';
                      return _TwoLineTile(
                        title:
                            '${row.labourName}${row.skillType.isNotEmpty ? ' · ${row.skillType}' : ''}',
                        subtitle:
                            '${row.projectName}${wage.isNotEmpty ? ' · $wage' : ''}',
                      );
                    }),
                  ],
                ),
        ),
      ],
    );
  }

  String _dateLabel(DateTime date) {
    return '${date.day}/${date.month}/${date.year}';
  }
}

// ── Shared Sub-Widgets ──

class _BarItem {
  final String label;
  final double value;
  final String unit;
  const _BarItem(
      {required this.label, required this.value, required this.unit});
}

class _OperationsBarChart extends StatelessWidget {
  final List<_BarItem> items;
  final Color barColor;
  const _OperationsBarChart(
      {required this.items, required this.barColor});

  @override
  Widget build(BuildContext context) {
    if (items.isEmpty) return const SizedBox.shrink();
    final maxValue =
        items.map((i) => i.value).reduce((a, b) => a > b ? a : b);
    final safeMax = maxValue > 0 ? maxValue : 1.0;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: items.map((item) {
        final ratio = item.value / safeMax;
        return Padding(
          padding: const EdgeInsets.only(bottom: 8),
          child: Row(
            children: [
              SizedBox(
                width: 90,
                child: Text(
                  item.label,
                  style: TextStyle(
                      fontSize: 11, color: AppColors.textHint),
                  overflow: TextOverflow.ellipsis,
                  maxLines: 1,
                ),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(3),
                  child: LinearProgressIndicator(
                    value: ratio,
                    minHeight: 12,
                    backgroundColor:
                        barColor.withValues(alpha: 0.1),
                    valueColor:
                        AlwaysStoppedAnimation<Color>(barColor),
                  ),
                ),
              ),
              const SizedBox(width: 8),
              Text(
                item.value > 0
                    ? '${item.value.toStringAsFixed(item.value == item.value.roundToDouble() ? 0 : 1)} ${item.unit}'
                    : '-',
                style: TextStyle(
                  fontSize: 11,
                  fontWeight: FontWeight.w600,
                  color: barColor,
                ),
              ),
            ],
          ),
        );
      }).toList(),
    );
  }
}

class _ReportCard extends StatelessWidget {
  final IconData icon;
  final String title;
  final Widget child;
  final bool isLoading;

  const _ReportCard({
    required this.icon,
    required this.title,
    required this.child,
    required this.isLoading,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(14),
        border:
            Border.all(color: AppColors.borderDark.withValues(alpha: 0.5)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, size: 18, color: AppColors.textSecondary),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  title,
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                        fontWeight: FontWeight.w700,
                      ),
                ),
              ),
              if (isLoading)
                const SizedBox(
                  height: 14,
                  width: 14,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
            ],
          ),
          const SizedBox(height: 14),
          child,
        ],
      ),
    );
  }
}

class _TwoLineTile extends StatelessWidget {
  final String title;
  final String subtitle;
  final String? trailing;

  const _TwoLineTile({
    required this.title,
    required this.subtitle,
    this.trailing,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                        fontWeight: FontWeight.w600,
                        color: AppColors.textPrimary,
                      ),
                ),
                const SizedBox(height: 2),
                Text(
                  subtitle,
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                        color: AppColors.textSecondary,
                        fontSize: 11,
                      ),
                ),
              ],
            ),
          ),
          if (trailing != null && trailing!.isNotEmpty)
            Text(
              trailing!,
              style: TextStyle(
                  fontSize: 11, color: AppColors.textHint),
            ),
        ],
      ),
    );
  }
}

class _EmptyRow extends StatelessWidget {
  final String message;
  const _EmptyRow({required this.message});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Text(
        message,
        style: TextStyle(fontSize: 12, color: AppColors.textHint),
      ),
    );
  }
}
